### ISSUE TITLE
Estimate Runtimes for various watersheds.

### ISSUE THREAD

**Issue by HenryGeorgist** [USACE/wat-api#17]

**Comment by rcozmyer** [comment]
I'm working on pulling in simulation runtimes from a bunch of the PFRA work areas as well as parameters that could be predictive (model area, # cells, RAS version, simulation length, fluvial/pluvial, etc)

**Comment by rcozmyer** [comment]
So far I've adapted a script to pull a bunch of parameters from HDF5 outputs files to grab what I think could be useful/predictive information about the RAS model and how long the run took. Next step is to figure out how to determine facts about the machine that ran the run (which might just be making inferences from the filepaths and hunting down cloud compute settings.

Here's an example of the output from the script if anyone has suggestions on what to pull. There's a bunch of stuff in here that's probably not necessary because its origin was as a QC tool to make sure that runs happened with the correct settings.

[QC_Script_Runtime_Results.xlsx](https://github.com/USACE/wat-api/files/8532548/QC_Script_Runtime_Results.xlsx)
)

**Comment by HenryGeorgist** [comment]
it seems like we would need to take that information and report out the total runtime (which i dont see in this summary) and then plot it by some of these parameters you do have. Thanks.

**Comment by rcozmyer** [comment]
For these plans, it's the runtime_hr at the end. I'll go ahead and run this
script on all of our PFRA runs and some other sets of model runs.

**Comment by HenryGeorgist** [comment]
ope - yep it is there, i just missed it.

**Comment by HenryGeorgist** [comment]
when you run these plans are you running the geometry preprocessor too?

**Comment by rcozmyer** [comment]
I can check and have it pull out the time for all of the different steps.

**Comment by HenryGeorgist** [comment]
![image](https://user-images.githubusercontent.com/7872881/164712892-9aa97ed3-c2b8-449d-a1d1-41fed61af853.png)

@rcozmyer I am struggling with how to best utilize the data. As far as I can tell it is not normalized to any particularly meaningful metric. There are many parameters that I believe would be creating high correlations. For instance, some matriculation of simtime, number of elements, number of cpus, and timestep probably would be the best unit of measure to compare to overall runtime, that way we would reduce the error in that relationship. Otherwise it is just a gee whiz type of plot.
